In [1]:
import pandas as pd
import numpy as np

In [2]:
# Dataset we'll use all day — sales data
data = {
  'order_id': [1,2,3,4,5,6,7,8,9,10],
  'customer': ['Arnav','Priya','Rahul','Arnav','Sneha',
               'Rahul','Meera','Priya','Arnav','Sneha'],
  'city': ['Pune','Mumbai','Delhi','Pune','Mumbai',
               'Delhi','Pune','Mumbai','Pune','Mumbai'],
  'product': ['Laptop','Phone','Tablet','Phone','Laptop',
               'Laptop','Tablet','Laptop','Tablet','Phone'],
  'sales': [85000, 45000, 32000, 42000, 91000,
               88000, 35000, 93000, 38000, 47000],
  'quantity': [1, 2, 1, 1, 1, 1, 2, 1, 2, 3],
  'discount': [0.1, 0.0, 0.15, 0.0, 0.2,
               0.1, 0.0, 0.05, None, 0.1],
  'order_date': ['2024-01-15','2024-01-22','2024-02-01',
               '2024-02-14','2024-02-28','2024-03-05',
               '2024-03-18','2024-03-25','2024-04-02','2024-04-10']
}

In [97]:
df=pd.DataFrame(data)
df.shape
df.head()

   order_id customer    city product  sales  quantity  discount  order_date
0         1    Arnav    Pune  Laptop  85000         1      0.10  2024-01-15
1         2    Priya  Mumbai   Phone  45000         2      0.00  2024-01-22
2         3    Rahul   Delhi  Tablet  32000         1      0.15  2024-02-01
3         4    Arnav    Pune   Phone  42000         1      0.00  2024-02-14
4         5    Sneha  Mumbai  Laptop  91000         1      0.20  2024-02-28

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 8 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   order_id    10 non-null     int64
 1   customer    10 non-null     object
 2   city        10 non-null     object
 3   product     10 non-null     object
 4   sales       10 non-null     int64
 5   quantity    10 non-null     int64
 6   discount    9 non-null      float64
 7   order_date  10 non-null     object
dtypes: float64(1), int64(3), object(4)
memory usage: 772.0+ bytes

In [7]:
df.describe()

       order_id         sales   quantity  discount
count  10.00000     10.000000  10.000000  9.000000
mean    5.50000  59600.000000   1.500000  0.077778
std     3.02765  25966.645272   0.707107  0.071200
min     1.00000  32000.000000   1.000000  0.000000
25%     3.25000  39000.000000   1.000000  0.000000
50%     5.50000  46000.000000   1.000000  0.100000
75%     7.75000  87250.000000   2.000000  0.100000
max    10.00000  93000.000000   3.000000  0.200000

In [8]:
df.columns

Index(['order_id', 'customer', 'city', 'product', 'sales', 'quantity',
       'discount', 'order_date'],
      dtype='object')

In [10]:
df.nunique()

order_id      10
customer       5
city           3
product        3
sales         10
quantity       3
discount       5
order_date    10
dtype: int64

In [11]:
df['sales']

0    85000
1    45000
2    32000
3    42000
4    91000
5    88000
6    35000
7    93000
8    38000
9    47000
Name: sales, dtype: int64

In [14]:
df[['customer','sales','city']]

  customer  sales    city
0    Arnav  85000    Pune
1    Priya  45000  Mumbai
2    Rahul  32000   Delhi
3    Arnav  42000    Pune
4    Sneha  91000  Mumbai
5    Rahul  88000   Delhi
6    Meera  35000    Pune
7    Priya  93000  Mumbai
8    Arnav  38000    Pune
9    Sneha  47000  Mumbai

In [15]:
df.iloc[0]

order_id               1
customer           Arnav
city                Pune
product           Laptop
sales              85000
quantity               1
discount             0.1
order_date    2024-01-15
Name: 0, dtype: object

In [17]:
df.iloc[:3]

   order_id customer    city product  sales  quantity  discount  order_date
0         1    Arnav    Pune  Laptop  85000         1      0.10  2024-01-15
1         2    Priya  Mumbai   Phone  45000         2      0.00  2024-01-22
2         3    Rahul   Delhi  Tablet  32000         1      0.15  2024-02-01

In [ ]:
df.iloc[0:3,0:2] #first 3 rows and two columns

   order_id customer
0         1    Arnav
1         2    Priya
2         3    Rahul

In [20]:
df.loc[0, 'sales']

np.int64(85000)

In [ ]:
df.loc[0:2,['customer','sales']]

  customer  sales
0    Arnav  85000
1    Priya  45000
2    Rahul  32000

In [22]:
df[df['sales']>50000]

   order_id customer    city product  sales  quantity  discount  order_date
0         1    Arnav    Pune  Laptop  85000         1      0.10  2024-01-15
4         5    Sneha  Mumbai  Laptop  91000         1      0.20  2024-02-28
5         6    Rahul   Delhi  Laptop  88000         1      0.10  2024-03-05
7         8    Priya  Mumbai  Laptop  93000         1      0.05  2024-03-25

In [23]:
df[(df['sales']>50000) & (df['city']=='Pune')]

   order_id customer  city product  sales  quantity  discount  order_date
0         1    Arnav  Pune  Laptop  85000         1       0.1  2024-01-15

In [25]:
df[(df['city']=='Mumbai')| (df['city']=='Pune') ]

   order_id customer    city product  sales  quantity  discount  order_date
0         1    Arnav    Pune  Laptop  85000         1      0.10  2024-01-15
1         2    Priya  Mumbai   Phone  45000         2      0.00  2024-01-22
3         4    Arnav    Pune   Phone  42000         1      0.00  2024-02-14
4         5    Sneha  Mumbai  Laptop  91000         1      0.20  2024-02-28
6         7    Meera    Pune  Tablet  35000         2      0.00  2024-03-18
7         8    Priya  Mumbai  Laptop  93000         1      0.05  2024-03-25
8         9    Arnav    Pune  Tablet  38000         2       NaN  2024-04-02
9        10    Sneha  Mumbai   Phone  47000         3      0.10  2024-04-10

In [26]:
#isin — cleaner way to filter multiple values
df[df['city'].isin(['Mumbai','Delhi'])]

   order_id customer    city product  sales  quantity  discount  order_date
1         2    Priya  Mumbai   Phone  45000         2      0.00  2024-01-22
2         3    Rahul   Delhi  Tablet  32000         1      0.15  2024-02-01
4         5    Sneha  Mumbai  Laptop  91000         1      0.20  2024-02-28
5         6    Rahul   Delhi  Laptop  88000         1      0.10  2024-03-05
7         8    Priya  Mumbai  Laptop  93000         1      0.05  2024-03-25
9        10    Sneha  Mumbai   Phone  47000         3      0.10  2024-04-10

In [27]:
df[~df['city'].isin(['Mumbai'])]

   order_id customer   city product  sales  quantity  discount  order_date
0         1    Arnav   Pune  Laptop  85000         1      0.10  2024-01-15
2         3    Rahul  Delhi  Tablet  32000         1      0.15  2024-02-01
3         4    Arnav   Pune   Phone  42000         1      0.00  2024-02-14
5         6    Rahul  Delhi  Laptop  88000         1      0.10  2024-03-05
6         7    Meera   Pune  Tablet  35000         2      0.00  2024-03-18
8         9    Arnav   Pune  Tablet  38000         2       NaN  2024-04-02

In [28]:
df.isnull().sum()

order_id      0
customer      0
city          0
product       0
sales         0
quantity      0
discount      1
order_date    0
dtype: int64

In [29]:
(df.isnull().sum()/len(df))*100

order_id       0.0
customer       0.0
city           0.0
product        0.0
sales          0.0
quantity       0.0
discount      10.0
order_date     0.0
dtype: float64

In [31]:
df[df['discount'].isnull()]

   order_id customer  city product  sales  quantity  discount  order_date
8         9    Arnav  Pune  Tablet  38000         2       NaN  2024-04-02

In [32]:
df.duplicated().sum()

np.int64(0)

In [33]:
df[df.duplicated()]

Empty DataFrame
Columns: [order_id, customer, city, product, sales, quantity, discount, order_date]
Index: []

In [34]:
df.drop_duplicates(inplace=True)

In [35]:
df.drop_duplicates(subset=['customer','product'],keep='first',inplace=True)

In [44]:
df.dtypes

order_id               int64
customer              object
city                  object
product               object
sales                  int64
quantity               int64
discount             float64
order_date    datetime64[ns]
dtype: object

In [ ]:
df['order_date']=pd.to_datetime(df['order_date'])

0   2024-01-15
1   2024-01-22
2   2024-02-01
3   2024-02-14
4   2024-02-28
5   2024-03-05
6   2024-03-18
7   2024-03-25
8   2024-04-02
9   2024-04-10
Name: order_date, dtype: datetime64[ns]

In [42]:
pd.to_numeric(df['quantity'])

0    1
1    2
2    1
3    1
4    1
5    1
6    2
7    1
8    2
9    3
Name: quantity, dtype: int64

In [45]:
df['month']=df['order_date'].dt.month

In [46]:
df['year']=df['order_date'].dt.year

In [48]:
df['day_of_week']=df['order_date'].dt.day_of_week
df['day_of_week']

0    0
1    0
2    3
3    2
4    2
5    1
6    0
7    0
8    1
9    2
Name: day_of_week, dtype: int32

In [49]:
df.rename(columns={'customer':'Customer_name','sales':'Revenue'})

,order_id,Customer_name,city,product,Revenue,quantity,discount,order_date,month,year,day_of_week
0,1,Arnav,Pune,Laptop,85000,1,0.10,2024-01-15,1,2024,0
1,2,Priya,Mumbai,Phone,45000,2,0.00,2024-01-22,1,2024,0
2,3,Rahul,Delhi,Tablet,32000,1,0.15,2024-02-01,2,2024,3
3,4,Arnav,Pune,Phone,42000,1,0.00,2024-02-14,2,2024,2
4,5,Sneha,Mumbai,Laptop,91000,1,0.20,2024-02-28,2,2024,2
5,6,Rahul,Delhi,Laptop,88000,1,0.10,2024-03-05,3,2024,1
6,7,Meera,Pune,Tablet,35000,2,0.00,2024-03-18,3,2024,0
7,8,Priya,Mumbai,Laptop,93000,1,0.05,2024-03-25,3,2024,0
8,9,Arnav,Pune,Tablet,38000,2,NaN,2024-04-02,4,2024,1
9,10,Sneha,Mumbai,Phone,47000,3,0.10,2024-04-10,4,2024,2

In [51]:
df['Revenue_after_discount']=df.apply(lambda row:row['sales']*(1-row['discount']), axis=1)
df['Revenue_after_discount']

0    76500.0
1    45000.0
2    27200.0
3    42000.0
4    72800.0
5    79200.0
6    35000.0
7    88350.0
8        NaN
9    42300.0
Name: Revenue_after_discount, dtype: float64

In [52]:
df['Revenue_after_discount']=df['sales']*(1-df['discount'])

In [54]:
# Categorise a numeric column using apply

df['sales_tier']=df['sales'].apply(
    lambda x:'High' if x>70000 else ('Mid' if x>40000 else 'Low')
)
df['sales_tier']

0    High
1     Mid
2     Low
3     Mid
4    High
5    High
6     Low
7    High
8     Low
9     Mid
Name: sales_tier, dtype: object

In [55]:
# Create a second DataFrame to join with
city_info = pd.DataFrame({
  'city': ['Pune', 'Mumbai', 'Delhi'],
  'region': ['West', 'West', 'North'],
  'tier': [1, 1, 1]
})

In [56]:
pd.merge(df,city_info,how='left')

,order_id,customer,city,product,sales,quantity,discount,order_date,month,year,day_of_week,Revenue_after_discount,sales_tier,region,tier
0,1,Arnav,Pune,Laptop,85000,1,0.10,2024-01-15,1,2024,0,76500.0,High,West,1
1,2,Priya,Mumbai,Phone,45000,2,0.00,2024-01-22,1,2024,0,45000.0,Mid,West,1
2,3,Rahul,Delhi,Tablet,32000,1,0.15,2024-02-01,2,2024,3,27200.0,Low,North,1
3,4,Arnav,Pune,Phone,42000,1,0.00,2024-02-14,2,2024,2,42000.0,Mid,West,1
4,5,Sneha,Mumbai,Laptop,91000,1,0.20,2024-02-28,2,2024,2,72800.0,High,West,1
5,6,Rahul,Delhi,Laptop,88000,1,0.10,2024-03-05,3,2024,1,79200.0,High,North,1
6,7,Meera,Pune,Tablet,35000,2,0.00,2024-03-18,3,2024,0,35000.0,Low,West,1
7,8,Priya,Mumbai,Laptop,93000,1,0.05,2024-03-25,3,2024,0,88350.0,High,West,1
8,9,Arnav,Pune,Tablet,38000,2,NaN,2024-04-02,4,2024,1,NaN,Low,West,1
9,10,Sneha,Mumbai,Phone,47000,3,0.10,2024-04-10,4,2024,2,42300.0,Mid,West,1

In [58]:
pd.merge(df,city_info,how='inner')

,order_id,customer,city,product,sales,quantity,discount,order_date,month,year,day_of_week,Revenue_after_discount,sales_tier,region,tier
0,1,Arnav,Pune,Laptop,85000,1,0.10,2024-01-15,1,2024,0,76500.0,High,West,1
1,2,Priya,Mumbai,Phone,45000,2,0.00,2024-01-22,1,2024,0,45000.0,Mid,West,1
2,3,Rahul,Delhi,Tablet,32000,1,0.15,2024-02-01,2,2024,3,27200.0,Low,North,1
3,4,Arnav,Pune,Phone,42000,1,0.00,2024-02-14,2,2024,2,42000.0,Mid,West,1
4,5,Sneha,Mumbai,Laptop,91000,1,0.20,2024-02-28,2,2024,2,72800.0,High,West,1
5,6,Rahul,Delhi,Laptop,88000,1,0.10,2024-03-05,3,2024,1,79200.0,High,North,1
6,7,Meera,Pune,Tablet,35000,2,0.00,2024-03-18,3,2024,0,35000.0,Low,West,1
7,8,Priya,Mumbai,Laptop,93000,1,0.05,2024-03-25,3,2024,0,88350.0,High,West,1
8,9,Arnav,Pune,Tablet,38000,2,NaN,2024-04-02,4,2024,1,NaN,Low,West,1
9,10,Sneha,Mumbai,Phone,47000,3,0.10,2024-04-10,4,2024,2,42300.0,Mid,West,1

In [59]:
# Join on different column names

pd.merge(df,city_info,left_on='city',right_on='city',how='left')

,order_id,customer,city,product,sales,quantity,discount,order_date,month,year,day_of_week,Revenue_after_discount,sales_tier,region,tier
0,1,Arnav,Pune,Laptop,85000,1,0.10,2024-01-15,1,2024,0,76500.0,High,West,1
1,2,Priya,Mumbai,Phone,45000,2,0.00,2024-01-22,1,2024,0,45000.0,Mid,West,1
2,3,Rahul,Delhi,Tablet,32000,1,0.15,2024-02-01,2,2024,3,27200.0,Low,North,1
3,4,Arnav,Pune,Phone,42000,1,0.00,2024-02-14,2,2024,2,42000.0,Mid,West,1
4,5,Sneha,Mumbai,Laptop,91000,1,0.20,2024-02-28,2,2024,2,72800.0,High,West,1
5,6,Rahul,Delhi,Laptop,88000,1,0.10,2024-03-05,3,2024,1,79200.0,High,North,1
6,7,Meera,Pune,Tablet,35000,2,0.00,2024-03-18,3,2024,0,35000.0,Low,West,1
7,8,Priya,Mumbai,Laptop,93000,1,0.05,2024-03-25,3,2024,0,88350.0,High,West,1
8,9,Arnav,Pune,Tablet,38000,2,NaN,2024-04-02,4,2024,1,NaN,Low,West,1
9,10,Sneha,Mumbai,Phone,47000,3,0.10,2024-04-10,4,2024,2,42300.0,Mid,West,1

In [60]:
# Sort by sales descending
df.sort_values('sales', ascending=False).head(5)

,order_id,customer,city,product,sales,quantity,discount,order_date,month,year,day_of_week,Revenue_after_discount,sales_tier
7,8,Priya,Mumbai,Laptop,93000,1,0.05,2024-03-25,3,2024,0,88350.0,High
4,5,Sneha,Mumbai,Laptop,91000,1,0.20,2024-02-28,2,2024,2,72800.0,High
5,6,Rahul,Delhi,Laptop,88000,1,0.10,2024-03-05,3,2024,1,79200.0,High
0,1,Arnav,Pune,Laptop,85000,1,0.10,2024-01-15,1,2024,0,76500.0,High
9,10,Sneha,Mumbai,Phone,47000,3,0.10,2024-04-10,4,2024,2,42300.0,Mid

In [62]:
df.sort_values(['city','sales'], ascending=True)

,order_id,customer,city,product,sales,quantity,discount,order_date,month,year,day_of_week,Revenue_after_discount,sales_tier
2,3,Rahul,Delhi,Tablet,32000,1,0.15,2024-02-01,2,2024,3,27200.0,Low
5,6,Rahul,Delhi,Laptop,88000,1,0.10,2024-03-05,3,2024,1,79200.0,High
1,2,Priya,Mumbai,Phone,45000,2,0.00,2024-01-22,1,2024,0,45000.0,Mid
9,10,Sneha,Mumbai,Phone,47000,3,0.10,2024-04-10,4,2024,2,42300.0,Mid
4,5,Sneha,Mumbai,Laptop,91000,1,0.20,2024-02-28,2,2024,2,72800.0,High
7,8,Priya,Mumbai,Laptop,93000,1,0.05,2024-03-25,3,2024,0,88350.0,High
6,7,Meera,Pune,Tablet,35000,2,0.00,2024-03-18,3,2024,0,35000.0,Low
8,9,Arnav,Pune,Tablet,38000,2,NaN,2024-04-02,4,2024,1,NaN,Low
3,4,Arnav,Pune,Phone,42000,1,0.00,2024-02-14,2,2024,2,42000.0,Mid
0,1,Arnav,Pune,Laptop,85000,1,0.10,2024-01-15,1,2024,0,76500.0,High

In [63]:
df['product'].value_counts()

product
Laptop    4
Phone     3
Tablet    3
Name: count, dtype: int64

In [64]:
df['city'].value_counts(normalize=True)

city
Pune      0.4
Mumbai    0.4
Delhi     0.2
Name: proportion, dtype: float64

In [ ]:
df.shape
df.dtypes
df.isnull().sum()

order_id                  0
customer                  0
city                      0
product                   0
sales                     0
quantity                  0
discount                  1
order_date                0
month                     0
year                      0
day_of_week               0
Revenue_after_discount    1
sales_tier                0
dtype: int64

In [67]:
df[df['sales']>60000]

,order_id,customer,city,product,sales,quantity,discount,order_date,month,year,day_of_week,Revenue_after_discount,sales_tier
0,1,Arnav,Pune,Laptop,85000,1,0.10,2024-01-15,1,2024,0,76500.0,High
4,5,Sneha,Mumbai,Laptop,91000,1,0.20,2024-02-28,2,2024,2,72800.0,High
5,6,Rahul,Delhi,Laptop,88000,1,0.10,2024-03-05,3,2024,1,79200.0,High
7,8,Priya,Mumbai,Laptop,93000,1,0.05,2024-03-25,3,2024,0,88350.0,High

In [69]:
df['discount'].fillna(df['discount'].median(),inplace=True)
df['discount'].isnull()

C:\Users\rguun\AppData\Local\Temp\ipykernel_21376\2714332286.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['discount'].fillna(df['discount'].median(),inplace=True)

0    False
1    False
2    False
3    False
4    False
5    False
6    False
7    False
8    False
9    False
Name: discount, dtype: bool

In [72]:
pd.to_datetime(df['order_date'])

0   2024-01-15
1   2024-01-22
2   2024-02-01
3   2024-02-14
4   2024-02-28
5   2024-03-05
6   2024-03-18
7   2024-03-25
8   2024-04-02
9   2024-04-10
Name: order_date, dtype: datetime64[ns]

In [105]:
df['order_date'] = pd.to_datetime(df['order_date'])
df['month'] = df['order_date'].dt.month

In [74]:
df['order_date'].dt.year

0    2024
1    2024
2    2024
3    2024
4    2024
5    2024
6    2024
7    2024
8    2024
9    2024
Name: order_date, dtype: int32

In [77]:
df.groupby('city')['sales'].sum().sort_values(ascending=True)

city
Delhi     120000
Pune      200000
Mumbai    276000
Name: sales, dtype: int64

In [82]:
df.groupby('product').agg(
    total_quantity=('sales','sum'),
    avg_sales=('sales','mean'),
    order_count=('sales','count')
)

         total_quantity     avg_sales  order_count
product
Laptop           357000  89250.000000            4
Phone            134000  44666.666667            3
Tablet           105000  35000.000000            3

In [81]:
df.head()

,order_id,customer,city,product,sales,quantity,discount,order_date,month,year,day_of_week,Revenue_after_discount,sales_tier
0,1,Arnav,Pune,Laptop,85000,1,0.10,2024-01-15,1,2024,0,76500.0,High
1,2,Priya,Mumbai,Phone,45000,2,0.00,2024-01-22,1,2024,0,45000.0,Mid
2,3,Rahul,Delhi,Tablet,32000,1,0.15,2024-02-01,2,2024,3,27200.0,Low
3,4,Arnav,Pune,Phone,42000,1,0.00,2024-02-14,2,2024,2,42000.0,Mid
4,5,Sneha,Mumbai,Laptop,91000,1,0.20,2024-02-28,2,2024,2,72800.0,High

In [111]:
df['net_revenue']=df['sales']*(1-df['discount'])
df.columns

Index(['order_id', 'customer', 'city', 'product', 'sales', 'quantity',
       'discount', 'order_date', 'month', 'net_revenue'],
      dtype='object')

In [86]:
df.head()

,order_id,customer,city,product,sales,quantity,discount,order_date,month,year,day_of_week,Revenue_after_discount,sales_tier,net_revenue
0,1,Arnav,Pune,Laptop,85000,1,0.10,2024-01-15,1,2024,0,76500.0,High,76500.0
1,2,Priya,Mumbai,Phone,45000,2,0.00,2024-01-22,1,2024,0,45000.0,Mid,45000.0
2,3,Rahul,Delhi,Tablet,32000,1,0.15,2024-02-01,2,2024,3,27200.0,Low,27200.0
3,4,Arnav,Pune,Phone,42000,1,0.00,2024-02-14,2,2024,2,42000.0,Mid,42000.0
4,5,Sneha,Mumbai,Laptop,91000,1,0.20,2024-02-28,2,2024,2,72800.0,High,72800.0

In [88]:
df.groupby('customer')['sales'].sum().sort_values(ascending=False).head(1)

customer
Arnav    165000
Name: sales, dtype: int64

In [92]:
new=pd.merge(df,city_info,on='city',how='inner')
print(new[['order_id','product','city','region']])

   order_id product    city region
0         1  Laptop    Pune   West
1         2   Phone  Mumbai   West
2         3  Tablet   Delhi  North
3         4   Phone    Pune   West
4         5  Laptop  Mumbai   West
5         6  Laptop   Delhi  North
6         7  Tablet    Pune   West
7         8  Laptop  Mumbai   West
8         9  Tablet    Pune   West
9        10   Phone  Mumbai   West

In [106]:
df.groupby('month')['sales'].sum().sort_values(ascending=False).nlargest(1)

month
3    216000
Name: sales, dtype: int64

In [102]:
df.columns

Index(['order_id', 'customer', 'city', 'product', 'sales', 'quantity',
       'discount', 'order_date'],
      dtype='object')

KeyError: 'date'

In [112]:
df['sales_tier']=df['net_revenue'].apply(
    lambda x:'High' if x>70000 else ('Mid' if x>40000 else 'Low')
)

In [115]:
df.groupby(['city','product'])['net_revenue'].sum().idxmax()

('Mumbai', 'Laptop')